name: mobile-exploration
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - matplotlib==3.8.2
    - numpy==1.26.3
    - scikit-learn==1.4.0
    - scikit-image==0.22.0